version: '3.8'
services:
  ratings:
    build: ./ratings/
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: "mongodb://mongodb:27017/ratings"
  mongodb:
    image: bitnami/mongodb:4.4.2-debian-10-r0
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
  bookinfo:
    build: ./productpage/
    ports:
      - "8081:9080"
  reviews:
    build: ./reviews/
    ports:
      - "8082:9080"
  details:
    build: ./details/
    ports:
      - "8083:9080"
